### ISSUE TITLE
Auto Allocate Armor on Mechs places the last armor point on the Right Leg instead of the CT`

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megameklab#105]
The scheme being used drops the last point of unused armor on the Right Leg. This is different insofar as every single previous version of MML would place that point on the CT or CT(R).

The Legs, Arms, L/R Torso should be equal... the extra point should go to the CT.

**Comment by neoancient** [comment]
It took a lot of trial and error to find an armor value that would reproduce this, but I happened on one just before giving up and asking for more information. The actual problem was that the way it split torso between front and rear sometimes resulted in rounding values up in a way that it ran out point to allocate before it got to the left leg, which is the final location.
