### ISSUE TITLE
LAM landing gear not placed correctly with compact engine or gyro.

### ISSUE THREAD

**Issue by snrdg102417** [MegaMek/megameklab#106]
On the HeavyMetal BattleMech Submissions forum is a challenge to make a BZK-F3 Hollander into a LAM.
I opened the Hollander file and made the changes to a LAM. I clicked the Validate Unit button the message Validation Passes. There are no messages Saving the file for the Hollander LAM does not display any messages. When I access the file a pop-up opens Message: Warning: Invalid unit, it might load incorrectly! Equipment that Failed to Load: Landing Gear. Opening Assign Criticals shown the landing gear but the weapons, ammo, heat sinks, and jump jets are present. The Gauss rifle and ammo are not shown even though they are in the Equipment tab.

[Hollander NS LAM.zip](https://github.com/MegaMek/megameklab/files/1468403/Hollander.NS.LAM.zip)

**Comment by xStormforgex** [comment]
Not sure this issue is closed.

The LAM Side Torso Landing Gear critical slots are disappearing when adding a Compact Engine, Compact Gyro, Heavy Duty Gyro, or Small Cockpit. The CT Landing Gear crit is also moving from the #1 critical slot down to the first open slot after adding one of the above items. 

Ex. in the case of the small cockpit from #1 CT slot to the #11 CT slot, Compact Gyro from the #1 CT slot to the #9 CT slot, etc.

**Comment by neoancient** [comment]
I didn't pay close enough attention and was removing all landing gear instead of just the center torso when adjusting its critical slot. Placing the landing gear directly after the engine and gyro section is intentional.
