### ISSUE TITLE
(49.6) Support vehicles incorrectly classified as tech-D at a minimum regardless of components

### ISSUE THREAD

**Issue by LAFisherGIS** [MegaMek/megameklab#1064]
### Environment
MML 49.6 Downloaded with Mekhq (also experienced in prior versions)
Windows
Temurin 11

### Description

For reasons unknown to me, the minimum tech level megameklab ascribes to support vehicles is tech D.

If I open megameklab and manually set all tech ratings for its subcomponents down to C, or even to A and B, the tech rating given for the vehicle remains D in the readouts given for it with no added components whatsoever.

This is directly at odds with the availability chart on page 280 of techmanual, which gives varying tech ratings for all manners of component and allows for the tech level scaling of these machines, with the only elements with mimimums of tech rating D or higher (heatsinks are erroneously reported as tech D on this page and only this page of current printings, this has since been errata'd) being the omni and ultralight hull mods, armor with BARs 8-10, and power amplifiers. Neither of the vehicle variations on display below contain any of these elements, nor are any of their ratings set to D ratings, and yet the vehicles are classified as tech D. Even the full version of the vehicle, being fusion powered, contains no power amplifiers and so should not be tech-D.

This issue recurs whenever a new support vehicle is designed using megameklab and whenever a TRO is exported.

![image](https://user-images.githubusercontent.com/92408705/158866657-45e3235d-cbc9-4c50-a847-e3498822b226.png)
![image](https://user-images.githubusercontent.com/92408705/158866718-0afd7541-2db7-4f77-b615-085bf5912f1a.png)
![image](https://user-images.githubusercontent.com/92408705/158866774-ea39a0d8-c579-49ab-800d-9f8371a615ce.png)
![image](https://user-images.githubusercontent.com/92408705/158867384-f3eb93d1-9747-4c3e-8703-1c1325941c1f.png)
![image](https://user-images.githubusercontent.com/92408705/158867432-a7a63d18-446d-47be-9ea7-3fe9af88b087.png)
![image](https://user-images.githubusercontent.com/92408705/158867464-36f92ff8-daaf-486a-87fb-71e33006f18f.png)

### Files
Errors have prevented me from directly attaching the relevant files to my report, so here is a repository containing them (note: the version of the stripped goblin't in the zip file was created before I set it to techs A and B for the sake of demonstration, and so is simply tech C with no attached components for the sake of demonstrating that the tech rating is being incorrectly set to D)

Despite what the name of the zip folder implies, it contains the file for the non-stripped version of the vehicle as well.

https://github.com/LAFisherGIS/MML_Support_Vee

**Comment by Zogundar** [comment]
Seeing this in Infantry and Tanks/Combat Vehicles too. TechManual states Foot Infantry as Tech Rating A, but even equipping them with primitive tomahawks (Tech Rating A) still results in at least Tech Rating C. I can get the Availability to change to all A's, but the lowest I've seen the actual Tech Rating go is C. Meanwhile a Flatbed Truck is Tech Rating E? With an ICE?

It looks like the current code for Support & Combat Vehicles and Infantry all have the right Tech Ratings for the base types, so something else must be raising the Tech Rating. I don't even see a mention of .setTechRating(RATING_D) in SupportTank.java so I'm not sure where or what the culprit is. Engines.java only has three E ratings in the code and they certainly aren't for ICE.
