### ISSUE TITLE
Physical Attack Table Encoding Error (Push attack)

### ISSUE THREAD

**Issue by jskelcher** [MegaMek/megameklab#1111]
### Environment
Both MekLab 0.48.0 & 0.49.8
MekHQ bundle
Windows 11
Java vendor Eclipse Adoptium 11.0.13

### Description

When exporting to PDF: A Mech _with_ tables, the Damage entry for the Push Attack in the Physical Attacks table is displayed as â€” rather than 0. This occurs in both Acrobat and in Chrome's PDF renderers. Tested with Eurostile and Arial font families.

Same issues occurs when printing a Mech directly from MegaMekLab itself.

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/8792585/megameklablog.txt)
![2022-05-28 20_19_54-Blackjack BJ-3 pdf - Adobe Acrobat Pro DC (32-bit)](https://user-images.githubusercontent.com/19839767/171030708-3209a444-e312-438b-a34a-9bfe953bba62.png)

**Comment by raelik** [comment]
This is happening because it's trying to print an em dash that was just dropped into the code as a UTF-8 literal, which Java doesn't support: https://github.com/MegaMek/megameklab/blob/97bbc31645e397c434b3fc726ec84854e1b020e8/megameklab/src/megameklab/printing/reference/PhysicalAttacks.java#L49

It's being interpreted as 3 distinct bytes (0xE2, 0x80, 0x94) and translated with presumably the default system encoding, I see something slightly different on my sheet.  The fix will almost certainly involve using a Java Unicode literal, like this:

`addRow(bundle.getString("push"), "-1", "\u2014");`

There may be other necessary steps after that, like ensuring the output encoding when printing has that character.  Given that we both see something slightly different here, I don't think that's the case.  UTF-8 would probably be the best option.

**Comment by raelik** [comment]
Actually, looks like that was all it needed. Just tested it, and that worked. I'll submit a PR.

**Comment by raelik** [comment]
Here's what it looks like in my fixed branch:

![image](https://user-images.githubusercontent.com/53844/171088395-9992b559-b583-4039-b67f-0dc5476dc136.png)
