### ISSUE TITLE
[0.49.8] Laser Insulator needs functionality to attach it to a specific weapon

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/megameklab#1151]
### Environment
MegaMekLab 0.49.8

### Description
If a Laser Insulator is equipped to a unit with more than one viable weapon in the weapon area, for example the right arm, the lab will read this as being valid. However, attempting to load the unit into MegaMekLab, MegaMek or MekHQ will cause a load issue as the Insulator needs to be linked to a single weapon rather than a section of the the unit. 

### Files
![image](https://user-images.githubusercontent.com/37005983/180614681-c10f2f05-da6b-49b6-9a35-ab33620fa370.png)
[Ref.txt](https://github.com/MegaMek/megameklab/files/9174191/Ref.txt) (Really an mtf)

**Comment by kchapinriddle** [comment]
This is a bug, but the cause is a little different than reported. The attached 'mech is invalid because PPCs aren't lasers, not because there's two of them in the same location. Hence the 'mech has a laser insulator with no matching laser in the location, which is a construction rule violation. Replace those PPCs with LLs and the 'mech works fine. 

The actual issue is that MegaMekLab validation doesn't ensure that every laser insulator has a corresponding laser - it'll let a 'mech with a laser insulator but no lasers pass validation. Which will fail later.

[Laser Insulator Test Actual Lasers Version.txt](https://github.com/MegaMek/megameklab/files/9174238/Laser.Insulator.Test.Actual.Lasers.Version.txt)
[Laser Insulator Test No Lasers Version.txt](https://github.com/MegaMek/megameklab/files/9174239/Laser.Insulator.Test.No.Lasers.Version.txt)

**Comment by HuntingTarg** [comment]
So would this be the same reason that MML does not properly calculate the Total Heat when laser insulators are appropriately placed?
![MegaMekLab bug Laser Insulators, validation, and calculated Total Heat](https://user-images.githubusercontent.com/53635722/217691408-a467f0da-d777-4356-aa25-3ddfef638d0f.jpg)

**Comment by HuntingTarg** [comment]
Side question (for users, not maintainers); is there a CBT rules citation or official ruling that says that Laser Insulators must be applied/attached to a specific weapon, or can they just be 'out there' to fill crit slots?  I looked [here](https://bg.battletech.com/forums/tactical-operations/) and couldn't readily find one.  This is relevant to this bug because if (and as long as) there isn't, then the unit should not be deemed invalid by MHQ/MML, it should just treat the unattached Laser Insulator(s) as independent equipment item(s); i,e, if an Insulator isn't 'paired' with a specific laser, it just takes up a (hittable) crit slot and 0.5 ton and does nothing else to the design, it shouldn't be treated as an illegal design.

**Comment by HammerGS** [comment]
It's well defined in TacOps:AUE pg 134. 

_and must always be placed in the **same location as the weapon they are insulating**. Units that do not use BattleMech critical hit space treat insulators as part of the weapon itself._

**Comment by HammerGS** [comment]
The bug here is in the calculation with us not applying the 1 point heat reduction.
