### ISSUE TITLE
Unable to start 0.49.8+ on linux

### ISSUE THREAD

**Issue by Hark0nnen** [MegaMek/megameklab#1188]
I am unable to start any version since 0.49.8 ( when switch from "lab" to "mml" happened )

```
Error: Unable to initialize main class megameklab.MegaMekLab
Caused by: java.lang.NoClassDefFoundError: megamek/client/ui/preferences/SuitePreferences

```
no logfile is produced

Debian Buster 
```
 java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb10u1, mixed mode, sharing)

```

0.49.7 and prior works

**Comment by JohnLangford** [comment]
I'm hitting the same issue with Ubuntu 20.04.

./mml-startup
Error: Unable to initialize main class megameklab.MegaMekLab
Caused by: java.lang.NoClassDefFoundError: megamek/client/ui/preferences/SuitePreferences

java -jar MegaMekLab.jar 
Error: Unable to initialize main class megameklab.MegaMekLab
Caused by: java.lang.NoClassDefFoundError: megamek/client/ui/preferences/SuitePreferences

java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
