### ISSUE TITLE
Mech printing issue on 0.43.5

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megameklab#119]
On Linux, I get errors finding the default templates for both bipeds and quads.

Looking in the recordsheets directory, I don't see the listed SVGs, regardless of capitalization.

I see those SVGs on the master branch of the repo - possible packaging issue?

It generates an empty PDF, but also shows these errors in the logs:

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/1566355/megameklablog.txt)

**Comment by LiamsGhost** [comment]
On Windows 10, using the print to pdf function results in an empty single page PDF.

**Comment by neoancient** [comment]
The problem here is that the expected font was missing. What had happened previously is that it would substitute the default system font. I attribute the fact that it's not doing that now to a change in the svg rendering library, which went unnoticed because it was only tested with the font installed and there was no particular reason to think that it had changed. I have been able to reproduce it by uninstalling the font on my system.

You can get printing working for now by installing the fonts found in data/fonts, though it should not be necessary to install particular fonts to get the printing to work. It should be possible to provide alternate fonts in the svg files, but the svg library is not using that data. I'm looking into whether there's a way to get it to work without producing and maintaining a custom version of the library.

**Comment by neoancient** [comment]
Reverted svgSalamander library to previous version that does not have the font bug.

**Comment by arlith** [comment]
Are you using svgSalamander from their website?  I've got a patch for the release that's required for Warship printing.  I believe I had committed a special version.  I suppose that only exists in the warship printing branch right now.

**Comment by arlith** [comment]
See: https://github.com/blackears/svgSalamander/pull/21

I have to imagine you encountered this issue as well.
