### ISSUE TITLE
NPE when deleting equipment from a crit slot

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megameklab#1287]
0.49.14 - On a BA, when adding a mag clamp to any location and then deleting it via the right-click menu, an NPE occurs.

**Comment by Sleet01** [comment]
Taking social lock.  I'll check this out.

**Comment by Sleet01** [comment]
Issue is caused by a bug in the BA-specific crit handling that we use only for MML, whereby multi-slot Mounted items of _any_ kind can cause an NPE because we try to create CriticalSlot() instances using indexes that don't exist in the BA's equipment lists (due to the weird special slot handling).
This can actually occur when deleting _any_ item while multi-slot equipment is installed, even a 1-slot weapon that does not show this issue on its own.

Fix will be to simply check for `unit.getEquipment(eqId)` returning null, and avoid recreating a slot in the table for that equipment in such a case.

There is also some cleanup in `CritListCellRenderer`.
