### ISSUE TITLE
Fixed-wing support vehicles get a Structural Integrity of 0

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megameklab#1320]
### Environment
Observed on MegaMek 49.14 and 48.0 from MekHQ, on Windows, Java 17.05.

### Description
Per TechManual p140, Fixed-Wing Support Vehicles recieve a Structural Integrity value equal to the unit's safe thrust. 
Instead, fixed-wing support vehicles I create receive a Structural Integrity (and Engine Rating) of 0:
![image](https://github.com/MegaMek/megameklab/assets/29113974/25212921-a7dd-4e3f-997e-96f9ca221906)

### Files
blk file for the above unit: [Test Fixed Wing.zip](https://github.com/MegaMek/megameklab/files/12828355/Test.Fixed.Wing.zip)

**Comment by gsparks3** [comment]
Support Vehicles of all types have had a slightly weird behavior for a while, where if you look at the summary view during construction, it leaves the engine rating at 0 instead of calculating it (and, it seems, derived values) properly. However, on save and reload, everything is fine.

By downloading the provided test file and viewing it in MML with no changes, I get this:
![image](https://github.com/MegaMek/megameklab/assets/59574316/4775d8aa-6465-4472-8556-4194afbfe06e)
