### ISSUE TITLE
Auto Sort Feedback (very low priority)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1343]
With more official RS produced have some feedback on our Autosort. 

Once the weapons are listed, if the last weapon is Ammo dependant the first ammo list should be it's ammo. 
![image](https://github.com/MegaMek/megameklab/assets/13752452/2279e353-ee9e-4f78-867d-586e39b9abb2)

Plasma Weapons (or other weapons that deal only heat) should always be last on the last

related: https://github.com/MegaMek/megameklab/pull/1036

**Comment by pavelbraginskiy** [comment]
Plasma cannons theoretically *should* already be the last weapon in the list most of the time, since weapons are sorted first by damage, but the code actually sorts the weapons by their short-range aerospace damage value. 

The short-range aerospace damage value for the plasma cannon is given as 10, while the normal damage value is -3. 

Why are mek weapons sorted by aerospace damage anyway? Sorting by the normal damage value seems obvious and would cause heat-only weapons to be sorted "correctly".

**Comment by HammerGS** [comment]
This sorting needs to match the guidelines as set out by CGL.
