### ISSUE TITLE
'Cargo Space' cannot be removed from canon units

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/megameklab#136]
Some canon units, e.g. the J-37 Ordnance Transport have built-in cargo space, described as: "Cargo Space (1 door) - 21 tons".

This equipment cannot be removed in Mek Lab, limiting the usefulness of these units as bonus vehicles in MekHQ AtB. Otherwise this cargo space could be refitted with weapons or troop space.

Not sure if a "Fixed Cargo Space" field (similar to "Fixed Troop Space") in the chassis section will do, or something more complicated is required.

Note: this also affects VTOLS (e.g.Ferret Light Scout VTOL (Cargo)") and conventional fighters (e.g. "Planetlifter Air Transport (Standard)") as well, and probably other unit types.

**Comment by neoancient** [comment]
There are really two issues here. The first is that vehicle cargo space cannot be edited. The second is that the J-37 is a support vehicle, and MML should not allow loading support vehicles for editing until it has support for the construction rules.

The simplest solution for the first issue would be to add a control for setting the amount of cargo space. This is an incomplete solution because it does not account for specialized bay types (liquid, livestock, refrigerated, etc.). Doing so would probably require adding a separate transport panel, which should not be too difficult.

The easiest way to deal with the second issue would be to use a popup alert informing the user that the operation is unsupported and refusing to load the unit. This is what currently happens if you try to load, for instance, a warship (though the message could be clearer). With vehicles this is less ideal as the combat and support vehicles are not distinguished in the unit selector and it's not clear until you try to load it whether it is supported or not. But because I plan to add support vehicle construction in the near future this may be tolerable for now.
