### ISSUE TITLE
Hidden Font or Symbol in RS

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1401]
This is coming the layout guru for CGL.

![image](https://github.com/MegaMek/megameklab/assets/13752452/0652a343-8cc5-461a-a099-b0167f98efee)

![image](https://github.com/MegaMek/megameklab/assets/13752452/7984b069-97fc-48cd-bdae-c2dc8c65c547)

They are hoping we can find it and remove, they think its hiding in framing somewhere.

**Comment by SJuliez** [comment]
This shows up as Zapf Dingbats on my system. It seems to be the checkmarks used for AP, leg attack etc. This has been present since at least 0.48. The checkmarks used in the SVG are normal text (no special font) but somehow the export system thinks it should translate them to a symbol font. I am fairly sure this is no setting or code on out part. If this absolutely needs to be removed from the PDF we could replace the checkmarks with an image.

**Comment by HammerGS** [comment]
They've requested we move to an image. 

[CheckmarkSymbol.zip](https://github.com/MegaMek/megameklab/files/14159925/CheckmarkSymbol.zip)
