### ISSUE TITLE
Adding items

### ISSUE THREAD

**Issue by Darelius** [MegaMek/megameklab#150]
Hello, im new here, i hope, this is correct here.

Is there any option to add own items?
Like the wolverine ER PPC or any "homemade" weapons to the system?

Or even adding XXL reactors to dropships or something like that?

I know, this isnt "normal" but many "rules" from the construction rules in battletech cantradict each other.
Sometimes very harsh (like internal structure or reactor system etc).

So i would like to change some creation "rules" or add some homemade items - is this somehow possible?

**Comment by NickAragua** [comment]
Unfortunately, there is no way to add new equipment to the game at this time without modifying code.

**Comment by Darelius** [comment]
Hmm - and is there a way to to "modify" the code temporarely so far?

**Comment by Dylan-M** [comment]
I'm afraid not. You'd have to write the Java code, and compile a custom version from source You would then have to try get that distributed to all your players. You can check out MegaMek/megamek#517, which is designed to add this functionality you're requesting. I plan on working it after we've got the stable out. For now closing this, for 2 reasons: It's a MM thing since all equipment defines are in MM (which MML uses as a library), and there is an open PR for such functionality already we should have any discussion of it there.
