### ISSUE TITLE
Mech Image not printing

### ISSUE THREAD

**Issue by fuzbuckle** [MegaMek/megameklab#152]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
MegaMekLab 0.43.9-RC3

### Description
Even though I have selected a fluff image for a Mech, and it shows up in the preview, the image does not print when I print the record sheet.  The default cockpit image remains present on the record sheet.

### Files
No error messages

**Comment by neoancient** [comment]
Please attach log and image files.

**Comment by fuzbuckle** [comment]
Here are the Log Files and Attached Record sheet.
[BlackKnight.pdf](https://github.com/MegaMek/megameklab/files/1891982/BlackKnight.pdf)
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/1891984/megameklablog.txt)
![black knight](https://user-images.githubusercontent.com/38213107/38524695-89fcc9c6-3c1d-11e8-9cd2-8bb851160c39.jpg)

**Comment by neoancient** [comment]
Just glancing at this I thought it was a problem I've seen with some png files not rendering correctly. Now that I've had time to look into it I see that it's somewhat simpler. The part of the file path relative to the installation directory was being repeated, so instead of looking in `data/images/fluff/mech` it's looking in `data/images/fluff/data/images/fluff/mech`. My fix is to check for the file relative to the installation directory first, then if not found there to add the path to the fluff image directory.
