### ISSUE TITLE
Adding MP also adds heatsinks up to max free

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megameklab#17]
Whether modifying a mech or creating a new one, if you add MP to the point that the engine can hold more than 10 free MML will auto add heatsinks up to the maximum the engine can hold without the player's input.

Create a new mech or modify a premade, reduce HS to 10 and increase MP till the engine can hold more than 10 or at least increase the # the engine can hold over the stock config and it will auto add heatsinks up to the max free.

**Comment by BLOODWOLF333** [comment]
This also occurs when changing the cockpit type.  Using the 0.3.27 bundle.

**Comment by arlith** [comment]
Looks like this one has been present since 6fd38ac7.  In that commit, `UnitUtil.updateAutoSinks(2)` was added, which is designed to ensure that the unit has the proper number of unallocated heatsinks.  However, it makes a faulty assumption at the end: if there are unused critical-free heatsinks, it adds more.  This is faulty because these critical-free heatsinks are not weight-free, and so they shouldn't be added.  I removed the code that adds them.

I found the code pretty confusing, but I'm pretty sure this doesn't have unintended side-effects.  To help in understanding, I renamed `UnitUtil.getBaseChassisHeatsinks` to `UnitUtil.getCriticalFreeHeatSinks` since that better describes what that method does.
