### ISSUE TITLE
Cannot assign silver bullet gauss ammo to dropship

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#181]
Not sure if this should have been two tickets? Didn't want to spam them. 
I figured it's both related to dropships.
### Environment
Stable 0.44
Java 8

### Description
1)
Autoassigning Quarters for Dropships assigns passengers both a standard crew quarter and a 2nd class passenger cabin. 
Example: 6 base Crew, 10 passengers needs 
[2 Offier Quarters, 4 Crew Quarters, and 10 2nd class quarters].
It allocates 2/14/10, though. 
Edit: While I'm at it, I assume this is known, but it's not possible to add officers with the button unless there already is a number bigger than 0 assigned. 

2)
I can't allocate Ammo for the SB-Gauss.
It's just not there. Not in "unavailable", either.

**Comment by neoancient** [comment]
Unrelated issues need to be in separate tickets.
The auto-assign has been rewritten during the development of the advanced aerospace feature to pay attention to types of quarters that are already assigned, so that should be fixed when advanced aerospace construction is merged. Since the fix for that issue is pending, I'm going to change the title on this one to track just the SB Gauss ammo.

**Comment by HammerGS** [comment]
Silver Bullet should be fixed here - https://github.com/MegaMek/megamek/commit/2b77e67ed30ea4e4d6e195103abfbddd830b5e70
