### ISSUE TITLE
Nova CEWS & heat sinks on vehicles

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#198]
### Environment
0.45.0

### Description
I found that in Megameklab that Nova CEWS don't require heat sinks in vehicles, but it they should:
https://bg.battletech.com/forums/index.php/topic,8778.msg609701.html#msg609701

**Comment by HammerGS** [comment]
Looks like the code in Server line 20140 is only checking for Mechs and Aerospace.  According to IO pg 66:
![image](https://user-images.githubusercontent.com/13752452/45259031-bfceff80-b380-11e8-827d-0e75dd4a967a.png)

Should be able to use them.

**Comment by neoancient** [comment]
The code is Server doesn't check heat on vehicles because they are heat neutral and are designed so that they cannot build up extra heat. The problem here is that when vehicles are constructed MML automatically calculates the additional weight for heat sinks needed for energy weapons and vehicular stealth armor, but not for the Nova CEWS.
