### ISSUE TITLE
0.1.56 Equipment Tab Display & Exceptions In Log

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megameklab#20]
(latest release) Im not sure if this is the same issue everyone else has been reporting, mine never froze on me just have been noticing that the equipment tab screen will not draw correctly and will only draw the various buttons when you mouse over where they should be: 

![mm0](https://cloud.githubusercontent.com/assets/16950832/16473941/f7123734-3e37-11e6-9d9e-2412bf097a8f.png)

Can still go into the other three tabs which work correctly.  And according to the log I guess it still has to do with the xstream.

Exception in thread "Mech Cache Loader" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/converters/Converter
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.converters.Converter
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/340542/megameklablog.txt)

**Comment by pheonixstorm** [comment]
Is that copy of MML packaged with HQ or is it the standalone download?

**Comment by BLOODWOLF333** [comment]
That is the MML that comes with the 0.3.30 bundle.  Could #16 have not been included even though the comments list it as an included fix?

**Comment by arlith** [comment]
Likely what's happening is that the way the MML jar resolves the XStream jar isn't working when MML is packaged for MHQ.

**Comment by arlith** [comment]
Alright, so this is specific to the MML packaged in the Windows release of MHQ.  Inside the packacing_utils directory in the MHQ repository there are `.4j.xml` files for each project.  In MHQ, the `dontWrapJar` option for launch4j is used, which means that the generated executables don't have the JAR file wrapped in them, instead the jar file exists in the lib directory.  This is so the different projects can resolve cross-project dependencies.  This is a difference between the `.4j.xml` files for MML and MM.  Because the jar files aren't wrapped, the classpath has to be set properly inside the `.4j.xml` file.  This was done for MM, but was not done for MML.  I've fixed this issue in MHQ.

**Comment by BLOODWOLF333** [comment]
He is back! :D
