### ISSUE TITLE
0.45.1 Clan Improved Autocannon 20 has no standard ammunition 

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#202]
When attempting to design an early clan mech, There was no listing for standard ammunition for the Improved Autocannon 20.

**Comment by neoancient** [comment]
From reading the rules (IO, p. 96) it doesn't look to me like improved A/Cs really warrant their own separate ammo type. @HammerGS ?

**Comment by LiamsGhost** [comment]
Probably not, but I can't give them standard AC 20 ammo either. :)

**Comment by neoancient** [comment]
It's just a question of how to fix them. Change the ammo type or add standard ImpAC munitions. I tagged Hammer because that's his area but he's not around much for the next few days.

**Comment by HammerGS** [comment]
Update on this one.  They are supposed to have their own ammo types. But I can't see why the Imp 20 isn't getting it's own ammo.  It will add some of the alternate ammos.

**Comment by KojimaStorm** [comment]
Turns out the ammo is still in the game it just doesn't show up in MML. If you want to build a unit with an Improved AC/20 that utilises standard IAC/20 ammo you'll need to manually add the ammo to the .mtf. The line is CLIMPAmmoAC20

![image](https://user-images.githubusercontent.com/38634529/52539630-27c9ad80-2d46-11e9-8d57-f28a97d63a9c.png)

Curiously enough, you can still move the ammo around in the MekLab environment. Removing it requires another .mtf edit to bring it back. But otherwise it works just fine

![image](https://user-images.githubusercontent.com/38634529/52539675-b2121180-2d46-11e9-90da-da2b95fd0cce.png)

![image](https://user-images.githubusercontent.com/38634529/52539683-c81fd200-2d46-11e9-8cec-33c76ceab923.png)

Hope this helps
