### ISSUE TITLE
0.45.1 Inner Sphere Endo Steel is unavailable to early clan mechs.

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#203]
There is no option to add inner sphere endo steel to clan mechs, even when it was the only endo steel option for those mechs. 

Clan Endo Steel does not become available until 2825 at the earliest, however clan technology dates back as early as 2815. There's no option to add inner sphere endo steel to a clan design, nor can you add it to a mixed tech (clan) design. Nor can you add early clan weapons to an inner sphere design. The only option for adding inner sphere endo steel to a clan mech is to set it to a year where mixed tech (inner sphere) designs are available (3045 or later based on trial and error), then set it to a mixed (inner sphere) design. This is necessary even if "show extinct tech" and "unofficial ignores year" are selected in configuration.

On a related note, making the year of production an integral, necessary part of the design process is an obnoxious feature that gets in the way of actually designing the mech, and "unofficial ignores year" apparently means "only sort of ignores year".

**Comment by neoancient** [comment]
Making the year an integral part of the design process is a necessity for canon designs, but it is not not a necessary part of it, since there is the option to ignore year. This particular issue has nothing to do with dates. MML treats IS equipment that has not yet gone extinct in the IS as Clan equipment during the transitional period. The problem is that the available structures are connected to the tech base, even for mixed (e.g. Clan mixed is a mixed tech unit with a Clan chassis, therefore internal structure with a Clan tech base). This breaks down when it comes to Clans using IS structure in mixed tech, which is something that they should be able to do at any point.

**Comment by LiamsGhost** [comment]
At best the date of introduction is a fluff point. Also, "Ignores Year" doesn't actually work the way you think it does. Even with it enabled, equipment and technology doesn't appear if the date of introduction is set before they were canonically available. You're still restricting people by the date of introduction even if they specifically enable the option to not be restricted.

**Comment by HammerGS** [comment]
I can tell you from experience. I get numerous requests from players to fix the intro dates. We’ve got threads about them on our forums. 

Today even had a post on the official forum about wrong dates.  When unit errata is posted or the MUL changes you can be sure it’s pointed out to me. 

Dates matter, and if you think they don’t your in the minority as far as our player base.

**Comment by neoancient** [comment]
It's not working for you because you have the tech level set to experimental. "Unofficial ignores year" only ignores the year if the tech base is set to unofficial. If it's not clear from the brief text next to the check box, it's spelled out clearly in the tooltip: "If the tech level is set to unofficial, the intro/extinct year will be ignored."

**Comment by LiamsGhost** [comment]
Ah, so it's just two layers of arcane bullshit, and ignore year actually means "ignore year, but only if you really mean it." got it.

**Comment by LiamsGhost** [comment]
Dave, I not sure you're familiar with confirmation bias. People who care about the dates are going to request fixing the dates. People who don't care about the dates aren't going to email you about not fixing the dates. Even I, who by now obviously consider the enforced date to be an obnoxious mess, never bothered to complain about it until now.
    On Monday, September 17, 2018, 5:27:14 PM PDT, Dave N <notifications@github.com> wrote:  
 
 
I can tell you from experience. I get numerous requests from players to fix the intro dates. We’ve got threads about them on our forums.

Today even had a post on the official forum about wrong dates. When unit errata is posted or the MUL changes you can be sure it’s pointed out to me.

Dates matter, and if you think they don’t your in the minority as far as our player base.
