### ISSUE TITLE
Heat usage indicator error on all streak and one-shot missiles

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#268]
### Environment
Ver 0.45.3
Windows 7

### Description
On Heat usage indicator of  MegamekLab(the middle on the bottom, along with Tonnage, Criticals, BV and Cost), picking all streak missils raise a half of heat, and all one-shot missils raise a quarter of heat. 

For example:

Streak SRM 2 actually generates 2 heat, but it only increase 1 on heat usage.
SRM4(OS) actually generates 3 heat, but it only increases 0.75 on heat usage.

**Comment by wildj79** [comment]
My knee jerk reaction to this is that this is intentional. Both of these weapon types are a little special. Streaks don't generate heat at all if they don't achieve a lock, and OS SRM's can only be fired, well, once. So, if you think about it, it's a little disingenuous to add there full heat calculation for this purpose. 

Also, this seems to be consistent with the written BV calculation rules from TechManual, starting on p. 302. Which, I assume, is what the original author of the code that does these calculations used when writing it.

> After finding the ’Mech Heat Efficiency, next find the total heat that the ’Mech would generate if it fired all its offensive weapons in a single turn. Multiply by 2 the heat points generated by Ultra autocannon, multiply by 6 the heat points generated by rotary autocannon, reduce by half the heat points generated by Streak SRMs and reduce to one-quarter the heat points generated by one-shot weapons.

TechManual, p. 303

**Comment by neoancient** [comment]
Agreed. The purpose is to indicate to the user the general heat profile, not the maximum amount of heat that the unit can generate in a turn. If that were the case, it would also add it movement heat.

**Comment by binaryspica** [comment]
Ah, that sounds reasonable. Thanks!

**Comment by assaultdoor** [comment]
Wait, if it doesn't add in movement heat, why does a 'Mech without jump jets automatically have 2 points of heat, a 'Mech with 10 jump jets automatically have 10 points of heat, and a 'Mech with 10 improved jump jets automatically have 5 points of heat?

**Comment by binaryspica** [comment]
> Wait, if it doesn't add in movement heat, why does a 'Mech without jump jets automatically have 2 points of heat, a 'Mech with 10 jump jets automatically have 10 points of heat, and a 'Mech with 10 improved jump jets automatically have 5 points of heat?

Running creates 2 points of heat for battlemech.

**Comment by assaultdoor** [comment]
Yes. But neoancient said above that it didn't include movement heat, and wasn't intended to. So, has its purpose changed? Is tracking movement heat a bug?
