### ISSUE TITLE
ASF Printing - Pips not patterned symmetrically.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#282]
Feedback from CGL.

The RS printed by 45.4 are creating an uneven pattern of Pips for the SI and Armor.

### Environment
What version of MekLab does your issue apply to?  45.4
What operating system are you using?  Windows

### Description
See images.

### Files
Desired output and was included in Tokasha.
![image](https://user-images.githubusercontent.com/13752452/55634857-95a9b880-577c-11e9-9621-74a115a20146.png)

Actual output submitted to CGL
![image](https://user-images.githubusercontent.com/13752452/55634910-b40fb400-577c-11e9-94d3-9e73ed885291.png)

**Comment by Maingunnery** [comment]
Possibly a related issue, in the current version 0.45.4 (1.8.0_211) my record sheets have pips missing in the wings, see old and new files: 

[3-45 Sulla Z new.pdf](https://github.com/MegaMek/megameklab/files/3269494/3-45.Sulla.Z.new.pdf)
[3-45 Sulla Z old.pdf](https://github.com/MegaMek/megameklab/files/3269495/3-45.Sulla.Z.old.pdf)

**Comment by Dragon41673** [comment]
Any update on this guys? My layout guy would like to know.

Thanks!

**Comment by neoancient** [comment]
If there were an update it would be posted here.

**Comment by Dragon41673** [comment]
Sorry...not used to this type of reporting system still.

Is there an ETA on the fix being implemented?

**Comment by neoancient** [comment]
The short answer is that we can rarely give an ETA on anything.

Including frequent contributers, we rarely have more than half a dozen active coders working on the project, but since we all do this as a hobby and have family and work responsibilities, there are usually around 1-3 people at any given time working across all three programs. Things het done when they get done and I can't give you any more than that. We do accept outside code contributions, so if anyone wants to tackle this before we get around to it we'll be happy to take a look at it.

**Comment by Dragon41673** [comment]
Ok thanks

**Comment by Maingunnery** [comment]
Question, should I report the missing armor pips as a separate issue?

**Comment by neoancient** [comment]
Y

> Question, should I report the missing armor pips as a separate issue?

Yes. The pip pattern is cosmetic and low priority, while missing pips are an actual bug  and are more likely to receive attention in a separate issue.
