### ISSUE TITLE
Ferro Fibrous and Mixed Tech issue

### ISSUE THREAD

**Issue by sartris** [MegaMek/megameklab#286]
Standalone .45.4
Java version 1.8.0_201
Platform Windows 10 10.0 (x86)

When selecting mixed-tech with a clan base, inner sphere ferro-fibrous armor is not available before 3040 and inner sphere prototype FF is not available before 3030 yet IS primitive armor is always available. It appears to be taking the reintroduced dates for that equipment instead of the original production dates. 

Also, you cannot set a unit to mixed-tech with an inner sphere base before 3045. With the introduction of prototype clan gear from IO (which is clan tech base), such an option is necessary to design Operation Klondike-era units that would have incorporated this gear into Star League units around 2820 or clan-possessed star league units incorporating clantech upgrades in the homeworlds.

**Comment by neoancient** [comment]
For purposes of tech availability, "extinct" means no longer manufactured rather than unavailable. By default it's filtered out but you can change this by going to File > Configuration and selecting "Show extinct tech" on the Tech Progression tab. That will give you access to cached SL equipment.

For practical purposes the tech base is irrelevant for mixed tech, so you should be able to create Klondike-era units as Clan mixed, even if they're conceptually a refit of an IS base unit.
