### ISSUE TITLE
Equipment tab does not refresh when unit type changes.

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/megameklab#299]
### Environment
0.45.4
Windows 10

### Description
Changing base type to or from LAM whilst editing a unit causes all values to reset to defaults but leaves the equipment listed in equipment tab, it is, however, not loaded/registered on the other and weightless.

**Comment by SVNaas** [comment]
Continuation, changing the Motive Type also causes the same issue.

**Comment by neoancient** [comment]
This is expected behavior. When changing from basic 'Mech to LAM or QuadVee, or between biped, quad, and tripod a new object of the correct type is created. The same happens when changing between tank and VTOL, or between standard and superheavy vehicles, aerospace/conventional fighter, dropship/small craft, or jumpship/warship/space station. The failure to clear the previous equipment from the equipment tab does need to be fixed, however.
