### ISSUE TITLE
UI elements do not allow enough area for text on Linux (Gnome 3/Fedora)

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megameklab#32]
![screenshot from 2016-09-16 18-53-46](https://cloud.githubusercontent.com/assets/7352852/18604198/3758df2e-7c3f-11e6-9a57-98114728fab1.png)

For example.  I've tried playing with different text sizes in gnome-tweak-tool but the top and bottom edges of text still tend to get cut off.

This is with MegaMekLab 0.1.58

**Comment by wildj79** [comment]
What is the default Sans-Serif font on your district?  You might try setting a different font.

**Comment by mhjacks** [comment]
I've tried DejaVu Sans and Catarell.  DejaVu is better in the "summary" section but both are awful (as above) in the lower right (unallocated etc).  Is it possible to set font properties for this app specifically?

**Comment by Dylan-M** [comment]
Curiously, as a fellow Fedora user, I've never seen this. But then again, I avoid the hideous monstrosity that is Gnome3. I run Fedora with the MATE Desktop Environment. I'll have to install the Gnome3 version into a VM to avoid contaminating my actual install ;)

**Comment by mhjacks** [comment]
That's fair.  GNOME 3 uses gtk3; MATE (I think) still uses gtk2.  I've got the rpmfusion freetype-freeworld version running with the normal stuff (rgba hinting etc).  I normally keep the default fonts; I have a few other Fedora (also GNOME 3, but I too can build MATE VMs to see if this is common across Fedora variants).  As you can see from the screenshot, it's not off by much.

Also should note - I'm using openjdk 1.8 from the main fedora repos to run it.

**Comment by mhjacks** [comment]
![screenshot from 2016-10-05 19-10-52](https://cloud.githubusercontent.com/assets/7352852/19136131/8dd17376-8b2f-11e6-8612-872974ed1d28.png)

Yes, the layout definitely looks different under MATE in a VM, and I don't see the "trimming" effect.

**Comment by mhjacks** [comment]
I've tried a few different configurations, including vanilla GNOME 3 (without freetype-freeworld), and with vanilla Cinnamon, Plasma, and MATE on default, out-of-the-box Fedora 24 installations.  The issue seems to track most closely with GNOME 3, even without the freetype-freeworld and "normal" font tweaks.  Cinnamon shows a bit of artifact, but not nearly as much as GNOME 3; MATE and Plasma show no issues.  Even changing to other fonts in GNOME 3 (i.e. Sans Regular, the font that is used in GTK2/MATE) the edges are clipped.  That suggests to me that the main difference is between how GTK2 and GTK3 render the same form.

I don't know much about the details of font configs, or how easy/hard this might be to account for in the Java layer.

**Comment by Dylan-M** [comment]
Thanks for the extra work on this, you've saved me some time. One more thing we should look into: Does this happen when using the MekLab inside of MHQ? If it does, try different look & feels from the available themes. If we've got MML themed (I can't recall offhand if it is), please try different look & feels directly as well. I have a feeling that it's because we make a "best guess" at the native L&F, and pick a poor one in your instance. Manually changing it may help.

**Comment by mhjacks** [comment]
Yep, that was it.  Any of the themes works except GTK+ (although the CDE one looks...like CDE, and weird on modern displays).

I usually use the products separately - I game with a local group, and I prefer MM and friends to simulate prior to our matches.  Is there a way to tell MML when loading what theme to use on the command line?  That would be a perfectly acceptable workaround for me.

**Comment by Dylan-M** [comment]
I don't believe there currently is, and really both issues should be fixed. Thanks for helping track it down.

**Comment by Hugehead** [comment]
Although there isn't a way to change the theme that's been exposed by the developers, it's actually possible to force Java to render Swing applications with different themes through _JAVA_OPTIONS flags. The one of interest in this case is -Dswing.systemlaf, which I believe can be pointed at any class that implements the Swing interface. I'm not sure if that's the right terminology since I'm not a Java person and was just looking for a solution to this myself. 

What I found is that if you export _JAVA_OPTIONS to be -Dswing.systemlaf=com.sun.javax.swing.plaf.metal.CrossPlatformLookAndFeel
it will force MML to run with the Metal theme, and with that theme all of the text is fine. I haven't extensively tested it but I think it should just work. You can just add the line
 `export _JAVA_OPTIONS=-Dswing.systemlaf=com.sun.javax.swing.plaf.metal.CrossPlatformLookAndFeel`
into lab.sh before it runs the jar so that it's not modifying the variable with any greater scope than necessary.
![screenshot from 2018-04-02 23-40-46](https://user-images.githubusercontent.com/4944125/38233408-5804e4ce-36cf-11e8-8cff-05cf8f30b145.png)

**Comment by Dylan-M** [comment]
@Hugehead That's not true at all. We definitely **do** expose look and feel in the applications. At least in some of them. MML may be the exception, but it would be very easy to add.

**Comment by Hugehead** [comment]
@Dylan-M I'm aware you do in Megamek and MekHQ, but since MML doesn't currently have a GUI to expose it, I believe that the `Dswing.systemlaf` flag is currently the only way to change it without modifying the code. It's a stopgap measure at best, but it does manage to resolve the issue until a contributor has time to create a proper GUI.

**Comment by Dylan-M** [comment]
Well, this is something that, as I mentioned, is super easy to add. I'll try and get it in before stable as this could be considered a bug in the UI.

**Comment by pmjdebruijn** [comment]
This issue occurs on Ubuntu as well.
