### ISSUE TITLE
Large shield messing with jump jets

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megameklab#33]
Attaching a zip.
[Mjölnr HMR-MJR.zip.zip](https://github.com/MegaMek/megameklab/files/509831/Mjolnr.HMR-MJR.zip.zip)

Lab 1.58 so if this got fixed in a new release let me know.

So seems that impact resistant armor makes the jets go crazy a bit.
I used cargo as place holders for the 4 jets I was trying to use.

Adding jets seems to cause issues, and switching to improved doesn't seem to work.

Trying to work around it by setting things to normal and adding 4 jets appears to work, BUT...
When adding the 4 jets in the assign criticals tab when you add a jet it makes a bunch more jets adding tonnage and slots, and you can't fix it by turning the number down from the first tab.

**Comment by Dylan-M** [comment]
This is _probably_ the same issue as #29

**Comment by MarcJC** [comment]
The two are similar but I think different enough to warrant additional care when testing due to the variation on the unexpected effects of the two bugs.  

29 deals with modular armor and this one deals with impact resistant armor.  They are selected from different areas in the program.  Also this bug continues to jump jets in the assign criticals tab, where 29 does not.  I feel that is a big enough difference in effect that they should be treated as different when testing.

But that's just my advice.

**Comment by Dylan-M** [comment]
I basically marked them that way because they're both likely to be in the same spot in the code: the refresh for jumpjets. And they're both errors with jumpjets+armor. Which leads me to believe they have the same root cause: issues with the handling of jumpjets period. This isn't the first time we've run into issues with how they're handled, and it probably needs re-written completely.

**Comment by neoancient** [comment]
The problem is not the armor. It's the large shield. MML is calculating the required number of jump jets based on the current jump MP instead of the unmodified jump MP. Since a 'Mech cannot jump with an intact large shield, the jump MP is always zero and MML adds the number of requested jump jets every time it refreshes the values. It should be possible to add jump jets to a 'Mech with a large shield, since they can be used if the shield is destroyed.
