### ISSUE TITLE
BV calculation incorrect on Industrial mech without advanced fire control

### ISSUE THREAD

**Issue by WEKarnesky** [MegaMek/megameklab#356]
### Environment
Megamek lab, 0.47.0, as released from the MekHQ release of the same version

### Description
The OBV calculation is not adjusting for industrial mechs that do not have advanced fire control.

Page Three of [the current BV calculation errata (PDF)](https://bg.battletech.com/wp-content/uploads/2018/11/TechManual-BV2.1-Rev2017.pdf) says:

> Multiply the Weapon Battle Rating by the Speed Factor to give the Offensive Battle Rating. Note:IndustrialMechs, unless equipped with Advanced Fire Control (see p. 69), multiply their Offensive Battle Rating by 0.9.

Here is an excerpt from MML's BV breakdown of the `Patron I LoaderMech`:

Total Weapons BV Adjusted For Heat: |   | 0.0
-- | -- | --
Misc Offensive Equipment: |   |  
Total Misc Offensive Equipment BV: |   | 0.0
Total Ammo BV: |   | 0.0
Add weight |   | +15.0
Final Speed Factor: |   | ***0.77***
Weapons BV * Speed Factor | 15.0 * ***0.77*** | = 11.55
Offensive BV + Defensive BV | 62.7 + 11.55 | = 74.25
Total BV * Cockpit Modifier | 74.25 * 1.0 | = 74.0
  |   | -------------

MML is correctly calculating a speed factor of 0.77, however, it is not factoring in the Industrial mech without advanced fire control and should be using a value of (0.77 x 0.9 =) 0.693

It should be noted that SSW has an additional modifier for being Primative that makes our calculation to be (0.77 x 0.85 = ) 0.6545 however we have a forum post to clarify whether that should still be there, and the MML team will probably want to pay attention to that answer as it isn't doing it either and there is no firm answer after talking to errata experts (i.e. Xotl) whether it should still be there or not.   https://bg.battletech.com/forums/index.php?topic=67268.0

Regardless of that 0.05 modifier, MML is definitely missing the fire control modifier.

**Comment by neoancient** [comment]
MML does apply the fire control modifier. This is an error in the unit file:
![Screenshot from 2019-10-19 14-18-56](https://user-images.githubusercontent.com/16927464/67150324-ba2e3380-f27b-11e9-8757-eae8f4348a70.png)

Once the cockpit type is corrected, the 0.9 multiplier is applied:
![Screenshot from 2019-10-19 14-19-17](https://user-images.githubusercontent.com/16927464/67150330-c87c4f80-f27b-11e9-9399-589a70ede744.png)
![Screenshot from 2019-10-19 14-19-34](https://user-images.githubusercontent.com/16927464/67150333-ca461300-f27b-11e9-92ff-f662391447b1.png)

There is an error in reporting that shows a zero for the weapon BV on that line because it uses the offensive BV, which hasn't been calculated yet at that point. That screen shot is from after fixing the reporting error. But the BV calculation is correct.
