### ISSUE TITLE
Engine free heatsinks set to zero when checking Omni option

### ISSUE THREAD

**Issue by monbvol** [MegaMek/megameklab#380]
##### Environment
Standalone 47.2
Windows 10 64 bit professional
Java version 1.8.0_221

### Description
When attempting to create a new Clan Omnimech when I check the box to make it an omnimech the number of heat sinks that can be mounted in the engine drops to zero.
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/3964645/megameklablog.txt)

### Files
I don't see any errors in the log file but it is included just in case.

**Comment by neoancient** [comment]
You have to indicate how many are part of the base chassis. Any that are not part of the base chassis are pod-mounted and always have to be assigned critical space even if the engine is large enough for them to be integrated if they were fixed.
![Screenshot from 2019-12-15 20-52-02](https://user-images.githubusercontent.com/16927464/70876045-be29b980-1f7d-11ea-92de-b44777851c62.png)

But I really appreciate that you opened an issue on this instead of just bringing it up on the forum, and included the log file just in case.
