### ISSUE TITLE
Dropship armor missing - Possible weight calculation issue.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#385]
Their seems to be an issues with armor weight calculations.

From Discord Post.
> As far as dropship armor values. When you load [most] dropships up, you need to alloticate a ton or two more armor to meet the armor value you already have.
> then when you save and reload the file... it repeats
> [For example, loading a Union in the provided files leaves you at 3599.5 tons instead of 3600 when saved, that half ton having disappeared from armor, which leaves it half a ton short on armor. You fix it, resave... reload and the half ton is missing again]
> Now when I load a 50kt design of [a friends] making... its missing 10 tons of armor. Its odd

If I load the Union I see this:
![image](https://user-images.githubusercontent.com/13752452/71221750-03563000-228b-11ea-972b-13dd75506b53.png)

It seems to happen more with dropships that have a whole number for armor tonnage and not a half ton of armor.

One note on the Union the armor values in MML are correct and take into account unpublished errata.

### Environment
What version of MekLab does your issue apply to?  current to repo (47.3)
What operating system are you using?  Windows

### Files
Best test is load the standard Union (2708)

**Comment by neoancient** [comment]
This was introduced when the hull/system-wide location was added. When the armor weight is calculated it subtracts free SI armor for all five locations instead of the four armored locations, then computes the armor weight based on the lower total. This also affects jumpships and space stations, but not warships, which account for the unarmored hull location along with the broadsides.
