### ISSUE TITLE
Some things that should't be pod-mountable are anyway

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#495]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, I can pod-mount the following items that should not be pod-mountable:

Blue Shield PFD
Mobile HPG
RISC Emergency Coolant System
Drone (Remote) Operating System
RISC (regular and improved)

The drone and RISC aren't specifically mentioned as not being pod-mountable, but TacOps has a rule against pod-mounting cockpits, so I assume that would apply to other control systems. I can put in a couple of rules questions on the forum to check, if you want.

**Comment by neoancient** [comment]
The drone (remote) operating system is not a cockpit. When you say RISC, do you mean the SRCS?

**Comment by assaultdoor** [comment]
Yeah, I meant SRCS. Twice, even.

**Comment by neoancient** [comment]
Blue shield, mobile HPG, and emergency coolant system were obviously overlooked. For now I'm leaving the drone operating system poddable, but will change it if the rules team decides it's not. Based on the description of the SRCS in the construction rules it appears to be an integral part of the cockpit rather than something that's added to it, so I'm making a judgement call and setting that as fixed only, again subject to change if the rules team says otherwise.

**Comment by HammerGS** [comment]
Based on this - https://bg.battletech.com/forums/index.php?topic=68384.msg1585452#msg1585452

Rules team is making will be making this ruling:
Answer: No, it's impossible to pod-mount a Drone (Remote) Operating System. It is indeed considered a type of cockpit and this rationale extends to non-Mech units also.
