### ISSUE TITLE
[Linux] Cache Not Working

### ISSUE THREAD

**Issue by ravionhawk** [MegaMek/megameklab#51]
While using MML in Ubuntu, the Cache Option (ctrl+u) can not find the "mechfiles" file and when manually searching (crtl+f) MML always starts back at the root.

Both of these work fine in Windows.

**Comment by neoancient** [comment]
I tried it on my Ubuntu laptop and I can't duplicate this.

**Comment by neoancient** [comment]
I have a number of versions installed in ~/MegaMek/. I run it from the command line within the installation directory, and that may be the difference.

**Comment by ravionhawk** [comment]
I'll fire up my machine later and get a screen shot of the path.

**Comment by Dylan-M** [comment]
This is a knowledge issue rather than a bug. The shell script, by default, creates ~/.megamek. If it exists already, it'll use the existing. Inside of ~/.megamek, it has symlinks to data folders. Yours are pointing to an old deleted location. This will soon be removed from the startup script because it breaks the *NIX paradigm. Dot folders in the home dir are for config files, not data.

**Comment by Dylan-M** [comment]
Bah, nevermind, I just noticed "megameklab". Not sure why it's doing that, and I cannot replicate either.

**Comment by ravionhawk** [comment]
Here is what I get on my Ubuntu and the location.

![screenshot from 2017-03-05 22-23-17](https://cloud.githubusercontent.com/assets/25833002/23595903/9ad57a50-01f3-11e7-8d87-4c74e3f329b7.png)
![screenshot from 2017-03-05 22-23-59](https://cloud.githubusercontent.com/assets/25833002/23595905/9ad7bc34-01f3-11e7-85e0-ba410b5633eb.png)
![screenshot from 2017-03-05 22-28-59](https://cloud.githubusercontent.com/assets/25833002/23595904/9ad79a6a-01f3-11e7-880c-73b0b5941453.png)

**Comment by ravionhawk** [comment]
The cache won't work and ctrl+f keeps resetting to the top.

**Comment by neoancient** [comment]
How are you running it? If I cd to the install dir (in this case ~/MegaMek/megameklab-0.43.1/) and run `java -jar MegaMekLab.jar`, it works correctly. If I cd to ~ and run `java -jar ./MegaMek/megameklab-0.43.0/MegaMekLab.jar` I get the same result that you are.

**Comment by ravionhawk** [comment]
I'm running it from the link you see on the desktop.

When I run it from the command line it does work, however, I need to be able to show players that have Linux that it works properly when using the desktop link.

We have a lot of people that changed to Ubuntu instead of Windows 10 around here and they aren't as savvy as us with Linux.

**Comment by wildj79** [comment]
What I did when I was running Debian was created a bash script on my desktop like this: `cd ~/megameklab && java -jar MegaMekLab.jar`. Or you could do this: `cd ~/megameklab && ./lab.sh`. Just make sure that `lab.sh` and the new script are executable.

**Comment by Dylan-M** [comment]
This should already work if the shortcut points to the shell script included with the release, and that shell script is made executable. The *NIX version expects some familiarity with the OS and how to use it beyond the beginner state. If it doesn't work just running the script and the script is made executable, I'm at a loss. The included script already includes this line:
`cd $(dirname "${BASH_SOURCE[0]}")`
Which makes the working directory the same directory the script is in.

There are 2 ways to make the script executable: set permissions on the file after it is extracted (either using the GUI or command line), or when it is extracted pass the `-p` flag to the `tar` command in order to preserve the permissions that are present when it is archived.

**Comment by ravionhawk** [comment]
I'll give those suggestions a try.

I just need to get it working for those that are not familiar with Linux. I guess this is going to be the new hurdle for Linux, having to make sure things work with the simple link for those leaving Windows with no Linux experience.

**Comment by HammerGS** [comment]
@ravionhawk you can continue the discussion on this in the Slack channels if required.
