### ISSUE TITLE
Weird margins on printing

### ISSUE THREAD

**Issue by sartris** [MegaMek/megameklab#746]
### Environment
Version - .47.7, .47.8, .47.9

Windows 10, Java 8 update 261

### Description
Since .47.7, printing either to my printer or PDF (including Adobe PDF, Microsoft PDF, and the XPS writer) with very large margins - a full inch. If you print in .47.6, the issue does not exist. I've included a PDF of each to show the difference.

[Archer 47.6.pdf](https://github.com/MegaMek/megameklab/files/5049106/Archer.47.6.pdf)
[Archer 47.7.pdf](https://github.com/MegaMek/megameklab/files/5049107/Archer.47.7.pdf)
[Archer 47.8.pdf](https://github.com/MegaMek/megameklab/files/5049108/Archer.47.8.pdf)
[Archer 47.9.pdf](https://github.com/MegaMek/megameklab/files/5049109/Archer.47.9.pdf)

**Comment by neoancient** [comment]
What are the margins set to in the print dialog?

**Comment by neoancient** [comment]
The change from 0.47.6 to 0.47.7 is that it allows the user to specify the margins, which were always fixed before.

The expected behavior is that you will get a cross-platform dialog that looks something like this:
![Screenshot from 2020-08-10 16-33-54](https://user-images.githubusercontent.com/16927464/89834016-a532d180-db27-11ea-905a-9dbc3fc47c91.png)
The margins are set on the Page Setup tab:
![Screenshot from 2020-08-10 16-37-06](https://user-images.githubusercontent.com/16927464/89834081-c09ddc80-db27-11ea-8a41-2c1f0047d449.png)

MML should be setting these to 0.25" by default.

**Comment by sartris** [comment]
ah ha. i see the problem now - i don't get that dialog. this is what i see. i don't get any margin options in the advanced settings either.

![print dialog](https://user-images.githubusercontent.com/27022730/89848557-040a4200-db4c-11ea-90b3-18e44458ce30.png)

**Comment by neoancient** [comment]
After checking with others, this appears to be platform dependent, which is a bit frustrating since the documentation specifically says this is the cross-platform version of the dialog. It's very difficult for me to troubleshoot OS-specific behavior since I only run Linux, but I do have another approach in mind that I think will take care of it and I can get other members of the dev team to test on Windows.

**Comment by sartris** [comment]
ok, i figured it would be something like that. i can stop combing the settings for a fix.
