### ISSUE TITLE
0.47.13 Primitive Armor on large spacecraft errors

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#821]
Program sometimes stumbles on primitive armor levels. In the colonial freighter file attached, the ship is only allocated 28.5 tons of armor, however on opening it throws up an invalid error stating it is carrying 29 tons of armor, and it is necessary to remove and then replace a half ton of armor to clear the phantom half ton. The error then reappears when loaded again. 

In the Tea Clipper file attached, the ship loads perpetually underweight by 1.5 tons even though that extra tonnage was previously allocated to the armor. Re-allocating the offending tonnage back to the armor, then saving and reloading results in the tonnage once again dropping by 1.5

[bug attachment.zip](https://github.com/MegaMek/megameklab/files/5507686/bug.attachment.zip)

**Comment by neoancient** [comment]
The first issue is due to an error in calculating the armor weight from the number of points, where it treats the free SI armor as if it's rounded separately.

The second issue is because MM only saves the number of points of armor and calculates the weight based on that. The extra 1.5 tons of armor don't give you any additional points.
