### ISSUE TITLE
Problem with PPC Capacitors in Mixed Tech Mechs and Vehicles

### ISSUE THREAD

**Issue by AldanFerrox** [MegaMek/megameklab#831]
When adding PPC Capacitors to Clan ER PPC's on Mixed Tech IS Mechs and Vehicles in version 0.47.14, saved files cannot be loaded without producing an error that makes it impossible to access the file (see screenshot)
![PPC Cap](https://user-images.githubusercontent.com/74641012/99486238-381fab00-2964-11eb-8bf2-61fd96c99f78.PNG)

**Comment by neoancient** [comment]
Include the unit file.

**Comment by AldanFerrox** [comment]
It seems to be an issue related to the year of construction. If I select the year 3145, it works, but not if I select the year 3075.
[Razorblade RAZ-02SA.zip](https://github.com/MegaMek/megameklab/files/5558829/Razorblade.RAZ-02SA.zip)
[Razorblade RAZ-02SB.zip](https://github.com/MegaMek/megameklab/files/5558838/Razorblade.RAZ-02SB.zip)

**Comment by HammerGS** [comment]
The IS is the first to develop PPC capacitors and the construction rules in TO AUE pg 149 "PPC Capacitors may be added to any **Inner Sphere** standard-scale PPC weapon".  The Clan don't develop the PPC Cap until 3101 at which point they can use them.

Basically using the current RAW you can't mix a Clan PPC with a Capacitor prior to 3101. I would recommend opening a rules query on the official forums - https://bg.battletech.com/forums/

**Comment by neoancient** [comment]
If the Clan and IS PPC are the same thing, then I don't see why a mixed tech unit couldn't attach an IS-manufactured PPC Capacitor to a Clan PPC at any date. If the Clan and IS capacitors are different, and only a Clan capacitor can attach to a Clan PPC, then we need to distinguish between them in the equipment. Artemis IV is an existing example of a component that has separate IS and Clan versions that are otherwise completely identical.

This post from 2011 seems to indicate that it's all the same thing: https://bg.battletech.com/forums/tactical-operations/(answered)-clan-erppc-ppc-capacitor/msg224786/#msg224786
This one from 2013 seems to indicate that there are separate IS and Clan versions: https://bg.battletech.com/forums/tactical-operations/(answered)-clan-erppc-ppc-capacitor/msg224786/#msg224786

If there is one type of capacitor but they didn't figure out how to connect it to a Clan PPC until 3101, then the unit should at least fail validation rather than saving fine and failing to load.

**Comment by NimoStar** [comment]
@HammerGS  Capacitors CAN be used on Clan ER PPCs. The thing about "compatible with IS PPC" was because mixed tech didin't even exist when those rules were originally written. Its a legacy wording thing intended to showcase this is an Inner Sphere technology.

**Comment by HuntingTarg** [comment]
_**Issue bump**_
Although the entry in _Tactical Operations_ pg. 337 identifies PPC Capacitors as an Inner Sphere technology, there are official rulings [here](https://bg.battletech.com/forums/tactical-operations/%28answered%29-clan-ppc-capacitors-in-3145/) and [here](https://bg.battletech.com/forums/rules-questions/answered-battlemech-manual-clan-ppc-capacitor/) that Clans can use PPC Capacitors about midway through the Dark Age.  So though the 'All' techbase designation is technically inaccurate, however the only difference in the technologies is the availability date.  AFAIC the devs who give generously of their time and energy can decide how to handle that issue.
Furthermore, since they are a component enhancement of an existing technology and not a new technology or weapon system themselves (much like Artemis IV), I do not know of any game reason that Inner Sphere techs cannot mount Inner Sphere PPC Capacitors on Clan salvage weapons.  I think the restriction to IS Techbase PPCs is, while well-meaning, erroneous.  The clans could mount Artemis IV on any compatible weapon system before Artemis IV was available to the Inner Sphere, so why can't the IS do the same to Clan PPCs with Capacitors?

**Comment by HuntingTarg** [comment]
It should also be mentioned that it is a bug on its own that MML validates a design, but then saves it with an error that makes the file unloadable.  That means that the code is not treating an item consistent with the dev's interpretation of the rules, rather than there being actual unclearness or inconsistency in the rules themselves.
[Mack MCK-06-X.pdf](https://github.com/MegaMek/megameklab/files/11280029/Mack.MCK-06-X.pdf)
![PPC Capacitor save error 01 - design validated](https://user-images.githubusercontent.com/53635722/233265537-409b833c-7239-429f-90be-f2ad04ca46c7.jpg)
![PPC Capacitor save error 02 - design saved](https://user-images.githubusercontent.com/53635722/233265539-25801509-dbd2-4c58-84eb-d516aff9580a.jpg)
![PPC Capacitor save error 03 - refresh cache](https://user-images.githubusercontent.com/53635722/233265540-f1b3d041-e53b-4003-86a8-8c2fc87430f0.jpg)
![PPC Capacitor save error 04 - design file not in cache](https://user-images.githubusercontent.com/53635722/233265542-34a61453-cf0d-40b0-814c-7ffd96b3e75f.jpg)
![PPC Capacitor save error 05 - design file found in custom directory](https://user-images.githubusercontent.com/53635722/233265543-bd1c02b1-06d2-44f5-ad03-789c408676ce.jpg)
![PPC Capacitor save error 06 - design file will not load due to error after being validated](https://user-images.githubusercontent.com/53635722/233265546-efef241b-8c5b-47d6-a206-831198e69553.jpg)

**Comment by HammerGS** [comment]
Can you post the MTF, and logs the RS doesn't really help us.

**Comment by HuntingTarg** [comment]
THX, slipped my mind yesterday. 😕

[PPC Capacitor bug Case Examples.zip](https://github.com/MegaMek/megameklab/files/11292078/PPC.Capacitor.bug.Case.Examples.zip)
There are two MTFs, one that goes with the screenshots I posted, another one that I used to generate a new log file, since the old one was lost to shutdown.  Everything is in the folder.

**Comment by HammerGS** [comment]
Clan and IS PPC share the same in game stats but differ in their intro.
![image](https://user-images.githubusercontent.com/13752452/233797728-722e92f0-d8b9-4922-90cb-237e6e4e4f2a.png)
In the image from the code you can see the IS PPC Cap is Advanced tech in 3060, and Standard in 3081. The next line shows the Clans get it in 3101 as a Standard piece of Tech. The reference to ALL in our code simply means IS and Clan will have this equipment.

Building a Mek with a IS tech Base in 3100 has the Cap.
![image](https://user-images.githubusercontent.com/13752452/233798076-774ad6e3-6ddd-4f64-a0c6-327a8d47b4b1.png)

A Clan only Base doesn't have it. 
![image](https://user-images.githubusercontent.com/13752452/233798097-46c451d6-51a2-40ee-978a-f9c5653efaaa.png)

But building either type of Mixed in 3100 does show. 
![image](https://user-images.githubusercontent.com/13752452/233798276-4092067a-afae-4334-9bf1-840d792ba3b2.png)
and
![image](https://user-images.githubusercontent.com/13752452/233798292-14dcecfc-006a-4f2b-bab0-1ca6e736f903.png)

But after 3101 the Clan only tech base has them .
![image](https://user-images.githubusercontent.com/13752452/233799377-d798de14-328e-4f52-bbff-df17d13539e6.png)


We'd need to rewrite the display just to display Tech Base IS from 3060-3100, then turn it to ALL after that. This would required coding resources we currently don't have. 

The loading issue with not identifying the Improved PPC or Enhanced PPC on load. I have a fix pushed (https://github.com/MegaMek/megamek/commit/422774bb1de56b1f837014896eda73dcf1d60194) and with that fix the attached unit files load no issue.
