### ISSUE TITLE
 MegaMek Lab - Infantry Weapons Removed in Errata

### ISSUE THREAD

**Issue by FrozenIceman01** [MegaMek/megameklab#89]
IS Weapon Updates

1.  The "Rifle (Federated-Barrett M42B)(Inferno Grenades)" that was listed in TM on page 350 was removed in the Tech Manual v3.0 Infantry Table Errata.  (Otherwise it is the most optimized damage/bv in the game.

2.  The M61A also lost its Inferno grenades

3.  The Farshot LRM has an inferno option

4.  Machine Gun Semi Portable is missing

5.  MRM launcher is no longer one shot and also has Inferno Ammo option

6.  Snub Nose PPC was removed

7.  SRM are no longer labeled one shot

Clan Weapon Updates

1.  AA Weapon MK 2 is not flagged as Clan in MML and should be

2.  Flamer and Flamer Heavy should be flagged as clan as well

3.  Machine Gun Protable, Semi Portable, and support are flagged as IS only, need to be flagged as both

4.  SRM Standard 2 shot, Heavy, and Light inferno options need to be flagged for Clan

5.  Support Laser (ER, Semi-Portable) needs to be added

All:

Vintage Gatling Gun, Machine Gun, Mini Gun, Wire Guided Missile launcher, Gungnir and Snub Nose should be removed as they currently have no rules behind them.  This should apply to all 0 BV items across the board.  For example there is a 0 BV Blade Shuriken in the program and a new revised weapon Thrown (Shuriken) in the TM errata (also for 0 BV).  I imagine it would be ideal if the names match.  We generated a similar program in excel and (I believe) we got all of the updated Weapon tables.  You could use that to export weapons.  Similarly it might be helpful to troubleshoot problems (it doesn't have as many safe guards in it as MML).

[Infantry Template 1.7.9 GB Flame Infantry.xlsx](https://github.com/MegaMek/megameklab/files/1328276/Infantry.Template.1.7.9.GB.Flame.Infantry.xlsx)

**Comment by HammerGS** [comment]
**IS Weapon Updates**
1.	The "Rifle (Federated-Barrett M42B)(Inferno Grenades)" that was listed in TM on page 350 was removed in the Tech Manual v3.0 Infantry Table Errata. (Otherwise it is the most optimized damage/bv in the game. _– Won’t remove since it can possibly break peoples custom units and save games._

2.	The M61A also lost its Inferno grenades _– Won’t remove since it can possibly break peoples custom units and save games._

3.	The Farshot LRM has an inferno option _– Fixed as part of the IO Implementation._

4.	Machine Gun Semi Portable is missing _– Fixed as part of the IO Implementation_

5.	MRM launcher is no longer one shot and also has Inferno Ammo option _– Fixed as part of the IO Implementation_

6.	Snub Nose PPC was removed _– You might  want to go look at AToW Companion pg 195_

7.	SRM are no longer labeled one shot _– We are follow the naming conventions as defined in IO, see pg 57 for SRM Launcher names._

**Clan Weapon Updates**
1.	AA Weapon MK 2 is not flagged as Clan in MML and should be – _Fixed as part of the IO Implementation._

2.	Flamer and Flamer Heavy should be flagged as clan as well – _Fixed as part of the IO Implementation._

3.	Machine Gun Portable, Semi Portable, and support are flagged as IS only, need to be flagged as both – _Fixed as part of the IO Implementation._

4.	SRM Standard 2 shot, Heavy, and Light inferno options need to be flagged for Clan – _Fixed as part of the IO Implementation._

5.	Support Laser (ER, Semi-Portable) needs to be added – _Fixed as part of the IO Implementation._

All:
Vintage Gatling Gun, Machine Gun, Mini Gun, Wire Guided Missile launcher, Gungnir and Snub Nose should be removed as they currently have no rules behind them.
_Again please review AToW Companion pg 195._ 

In addition we have access to official contacts to clarify things that could appear in future errata.
This should apply to all 0 BV items across the board. For example there is a 0 BV Blade Shuriken in the program and a new revised weapon Thrown (Shuriken) in the TM errata (also for 0 BV).  
_See notes above about possibly breaking peoples games._

I imagine it would be ideal if the names match. We generated a similar program in excel and (I believe) we got all of the updated Weapon tables. You could use that to export weapons. Similarly it might be helpful to troubleshoot problems (it doesn't have as many safe guards in it as MML).

_Overall these issues have been addressed in the pending Dev Release (0.43.4)_

**Comment by FrozenIceman01** [comment]
For Items 1, 2 would it make sense to set the BV to 0?  Such that in the
future moving forward units can not be built using illegal rules?

For the naming scheme, would it be possible to have some element to
recognize the previous name scheme on a load and convert it to the new
scheme per the legal rules to reduce confusion to new players (and then on
re-save it uses the new correct nomenclature?

For the AoTW companion, those rules are strictly for the RPG, they do not
have BV nor damage conversions to the Total Warfare native.  Should they
really be usable in MML?

-Andrew

**Comment by HammerGS** [comment]
Items 1 and 2 - I'll look into having the rules levels on those weapons moved to Unofficial at a later release.

Regarding the naming mechanism, the weapons internal names (which MML uses to find the weapons) haven't changed only the names showing to the player to match IO. Weapons and equipment are stored in the blk files with this name.

Regarding AToW Companion (admittedly without BV)
![image](https://user-images.githubusercontent.com/13752452/31061186-68226586-a6db-11e7-8553-506dc71e57cc.png)

**Comment by FrozenIceman01** [comment]
Good Idea for 1 and 2!

Ya, I was mostly commenting on making sure the front facing names match
what is in the tech manual such that when they do print a new version there
isn't any confusion..

Ya, I've got a 2012 hard copy of my AToW companion but I don't see that
table (mine is on page 174) and it is written in the Time of War
nomenclature (Equipment Ratings, C-Bills, Mass/Reload).  I did some quick
scans but I didn't see the excerpt that you have above in it (but I may
have missed it).

**Comment by HammerGS** [comment]
Ya, I've got a 2012 hard copy of my AToW companion but I don't see that table (mine is on page 174) and it is written in the Time of War nomenclature (Equipment Ratings, C-Bills, Mass/Reload).  I did some quick
scans but I didn't see the excerpt that you have above in it (but I may have missed it).

As mentioned pg 195 of the Hard Copy and PDF have that table.

**Comment by FrozenIceman01** [comment]
I stand Corrected, thank you!

**Comment by FrozenIceman01** [comment]
With the new release that broke previous Save Games, did the elements that wouldn't be removed because of breaking custom units and save games get implemented?
